trigger:
  - main

pool:
  name: "Default"

variables:
  Major: 1
  Minor: 5
  BuildCounter: $[counter('',4)]
  PatchSeed: $[format('{0}.{1}', variables['Major'], variables['Minor'])]
  Patch: $[counter(variables['PatchSeed'], 0)]

# Updated Minor from 1 to 2
# Add StagePatch
  StageMajor: 1
  StageMinor: 4
#  StagePatchSeed: $[format('{0}.{1}s', variables['StageMajor'], variables['StageMinor'])]
#  StagePatch: $[counter(variables['StagePatchSeed'], 0)]

steps:
- script: |
    echo "Major: $(Major)"
    echo "Minor: $(Minor)"
    echo "Patch: $(BuildNumber)"
    echo "Regular Release $(Major).$(Minor).$(Patch) using seed $(PatchSeed)"
    echo "Stage Release $(StageMajor).$(StageMinor).$(StagePatch) using seed $(StagePatchSeed)"
    echo "$(BuildCounter)"
  displayName: 'Show Variables'
