trigger:
  - main

pool:
  name: "Default"

variables:
  Major: 1
  Minor: 3
  BuildCounter: $[counter('',4)]
  Patch: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 0)]

# Updated Minor from 1 to 2
# Add StagePatch
  StageMajor: 1
  StageMinor: 2
  StagePatch: $[counter(format('{0}.{1}', variables['StageMajor'], variables['StageMinor']), 0)]

steps:
- script: |
    echo "Major: $(Major)"
    echo "Minor: $(Minor)"
    echo "Patch: $(BuildNumber)"
    echo "Regular Release $(Major).$(Minor).$(Patch)"
    echo "Stage Release $(StageMajor).$(StageMinor).$(StagePatch)"
    echo "$(BuildCounter)"
  displayName: 'Show Variables'
